// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCy6vnbeWF1ohsC4-idETzk2tJyv8ubZ9E',
    appId: '1:268826059910:web:17f5c7123a493fef3a9d07',
    messagingSenderId: '268826059910',
    projectId: 'to-do-app-c08d8',
    authDomain: 'to-do-app-c08d8.firebaseapp.com',
    storageBucket: 'to-do-app-c08d8.appspot.com',
    measurementId: 'G-TQ6PRBQNZJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBUqS7vnOBGuN84pIvyiv3Y283UWPkR2u0',
    appId: '1:268826059910:android:dcecf2271cfb9d383a9d07',
    messagingSenderId: '268826059910',
    projectId: 'to-do-app-c08d8',
    storageBucket: 'to-do-app-c08d8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBLSVuDzKmc0C_d4tx-E_Bw1UCi65Y1IQY',
    appId: '1:268826059910:ios:b85e75c02f3e06633a9d07',
    messagingSenderId: '268826059910',
    projectId: 'to-do-app-c08d8',
    storageBucket: 'to-do-app-c08d8.appspot.com',
    iosBundleId: 'com.example.todoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBLSVuDzKmc0C_d4tx-E_Bw1UCi65Y1IQY',
    appId: '1:268826059910:ios:b85e75c02f3e06633a9d07',
    messagingSenderId: '268826059910',
    projectId: 'to-do-app-c08d8',
    storageBucket: 'to-do-app-c08d8.appspot.com',
    iosBundleId: 'com.example.todoApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCy6vnbeWF1ohsC4-idETzk2tJyv8ubZ9E',
    appId: '1:268826059910:web:8db7b181b5310deb3a9d07',
    messagingSenderId: '268826059910',
    projectId: 'to-do-app-c08d8',
    authDomain: 'to-do-app-c08d8.firebaseapp.com',
    storageBucket: 'to-do-app-c08d8.appspot.com',
    measurementId: 'G-BM273M2DXE',
  );
}
